sources:
  - name: ajna
    handler:
      graphql:
        endpoint: "{context.url:https://api.thegraph.com/subgraphs/name/halaprix/gajna}"

documents:
  - ./queries/weekly.graphql
  - ./queries/daily.graphql